epochs=list(range(1,len(losses)+1))
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs, losses, marker='o')
plt.title('Loss vs Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)


plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(times, losses, marker='o')
plt.title('Loss vs Time')
plt.xlabel('Time')
plt.ylabel('Loss')
plt.grid(True)